on: [push]
jobs:
  auto_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Build Changelog"
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          fromTag: "v0.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}
