on: [push]
jobs:
  auto_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Build Changelog"
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          base-ref: "v0.0.0"
          myToken: ${{ secrets.GITHUB_TOKEN }}
