on: [push]
jobs:
  auto_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Build Changelog"
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          fromTag: "2d314b32d0a64cf37e79ea2362db8953af1b12af"
          token: ${{ secrets.GITHUB_TOKEN }}
